### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
POST http://localhost:8080/api/v1/user
Content-Type: application/json

{
  "username": "Bathi",
  "email": "bathiya@gmail.com",
  "password": "BathiAyya123",
  "firstName": "Bathiya",
  "lastName": "Thisera",
  "isActive": true,
  "workspaces": [
    {
      "name": "My First Workspace",
      "description": "This is Bathiya's personal workspace",
      "visibility": "PRIVATE"
    }
  ]
}
