### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### Create User (Signup)
POST http://localhost:8080/api/v1/user/signup
Content-Type: application/json

{
  "username": "Shehan",
  "email": "shehan@gmail.com",
  "password": "password123",
  "firstName": "Shehan",
  "lastName": "Kaushalya",
  "isActive": true
}

### Signin User
POST http://localhost:8080/api/v1/user/signin
Content-Type: application/json

{
  "email": "shehan@gmail.com",
  "password": "password123"
}

### Create Workspace
POST http://localhost:8080/api/v1/workspaces?ownerId=a753f2ca-7683-4f4d-8a5f-710181fd659e
Content-Type: application/json

{
  "name": "Project Projekto",
  "description": "Workspace for Project 404NOTFOUNDUS",
  "visibility": "PUBLIC"
}

### Get User Workspaces
GET http://localhost:8080/api/v1/workspaces/user/78d0927a-be0f-423b-a804-75ace8dc0161
Content-Type: application/json

### Get Workspace by ID
GET http://localhost:8080/api/v1/workspaces/58e0c9ca-0182-42c9-897d-62f7d97cad95
Content-Type: application/json

### Update Workspace
PUT http://localhost:8080/api/v1/workspaces/99778641-ca38-4b9b-ae2e-260b3eb8496b?ownerId=7e394119-8c39-4fa0-a3e5-2385afc83fe1
Content-Type: application/json

{
  "name": "Project Alpha Updated",
  "description": "Updated description",
  "visibility": "PRIVATE"
}

### Add Member to Workspace (Return Updated Workspace)
POST http://localhost:8080/api/v1/workspaces/58e0c9ca-0182-42c9-897d-62f7d97cad95/members/c9c98e6a-1495-42a2-a0f7-2af9540edffd
Content-Type: application/json



### Remove Member from Workspace
DELETE http://localhost:8080/api/v1/workspaces/58e0c9ca-0182-42c9-897d-62f7d97cad95/members/c9c98e6a-1495-42a2-a0f7-2af9540edffd
Content-Type: application/json

### Delete Workspace
DELETE http://localhost:8080/api/v1/workspaces/58e0c9ca-0182-42c9-897d-62f7d97cad95
Content-Type: application/json


### Create Board
POST http://localhost:8080/api/v1/boards
Content-Type: application/json

{
  "name": "Project Planning Board",
  "description": "Board for sprint planning",
  "visibility": "PUBLIC",
  "workspaceId": "f4b909ce-f919-4263-9bb9-19d04ac561ce",
  "createdBy": "a753f2ca-7683-4f4d-8a5f-710181fd659e"
}

### Get Boards by Workspace
GET http://localhost:8080/api/v1/boards/workspace/f4b909ce-f919-4263-9bb9-19d04ac561ce


### Get Board by ID
GET http://localhost:8080/api/v1/boards/645c4497-0dd3-4bf2-a5d1-4a50dbf6f3ef

### Update Board
PUT http://localhost:8080/api/v1/boards/645c4497-0dd3-4bf2-a5d1-4a50dbf6f3ef
Content-Type: application/json

{
  "name": "Updated Board Name",
  "description": "Updated description",
  "visibility": "PRIVATE",
  "workspaceId": "11111111-1111-1111-1111-111111111111",
  "createdBy": "22222222-2222-2222-2222-222222222222"
}

### Delete Board
DELETE http://localhost:8080/api/v1/boards/645c4497-0dd3-4bf2-a5d1-4a50dbf6f3ef



### Create List API
POST http://localhost:8080/api/v1/lists
Content-Type: application/json

{
  "title": "To Do",
  "boardId": "645c4497-0dd3-4bf2-a5d1-4a50dbf6f3ef"
}